default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TaskManagement_app_development

test:
  <<: *default
  username: TaskManagement_app
  database: TaskManagement_app_test

production:
  <<: *default
  database: TaskManagement_app_production
  username: TaskManagement_app
  password: <%= ENV['TASKMANAGEMENT_APP_DATABASE_PASSWORD'] %>